#
# Copyright (c) 2025 by Delphix. All rights reserved.
#

repos:
  - repo: local
    hooks:
      - id: check-template-names
        name: Check if the ADF pipeline's template file and directory names are as per the convention.
        entry: python ./scripts/pre-commit/check_names.py
        language: python
        always_run: true
        pass_filenames: false
        verbose: true
        additional_dependencies:
          - PyYAML
          - packaging
      - id: sql-json-formatter
        name: Format SQL and json files
        entry: python ./scripts/pre-commit/format_sql_json.py
        language: python
        always_run: true
        pass_filenames: false
        verbose: true
        additional_dependencies:
          - PyYAML
          - sqlparse
          - packaging
      - id: check-version
        name: Check if the version number has been updated in the VERSION.md file.
        entry: python ./scripts/pre-commit/check_version.py
        language: python
        always_run: true
        pass_filenames: false
        verbose: true
        additional_dependencies:
          - PyYAML
          - packaging
      - id: validate-changelog
        name: Verify if CHANGELOG.md has been updated
        entry: python ./scripts/pre-commit/validate_changelog.py
        language: python
        always_run: true
        pass_filenames: false
        verbose: true
        additional_dependencies:
          - PyYAML
          - packaging
      - id: validate-migration-scripts
        name: Validate migration scripts
        entry: python ./scripts/pre-commit/validate_migration_scripts.py
        language: python
        always_run: true
        pass_filenames: false
        verbose: true
        additional_dependencies:
          - PyYAML
          - packaging