repos:
  - repo: local
    hooks:
      - id: changelog_verify
        name: Verify if CHANGELOG.md has been updated
        entry: python ./scripts/pre-commit/validate_changelog_update.py
        language: python
        always_run: true
        pass_filenames: false
        verbose: true
        additional_dependencies:
          - PyYAML
