#
# Copyright (c) 2025 by Delphix. All rights reserved.
#

repos:
  - repo: local
    hooks:
      - id: validate-changelog
        name: Verify if CHANGELOG.md has been updated
        entry: python ./scripts/pre-commit/validate_changelog.py
        language: python
        always_run: true
        pass_filenames: false
        verbose: true
        additional_dependencies:
          - PyYAML
