name: Pre-commit Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # For PR events, checkout the actual branch
        ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    
    # Add this step to ensure proper git state
    - name: Setup git for pre-commit
      run: |
        COMMIT_AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
        COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
        git config --global user.name "$COMMIT_AUTHOR_NAME"
        git config --global user.email "$COMMIT_AUTHOR_EMAIL"
        echo "Git configuration set:"
        echo "User name: $COMMIT_AUTHOR_NAME"
        echo "User email: $COMMIT_AUTHOR_EMAIL"
    
    - name: Run pre-commit
      run: pre-commit run --all-files
